# Generated by Django 3.2.7 on 2021-09-12 20:57
from django.db import migrations
def create_site(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Site = apps.get_model('sites', 'Site')
    # create new site
    Site.objects.create(domain="test.co", name= 'Test')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_site)
    ]
